[
    {
        "model_creator":{
            "class":"flexible_keras.FlexibleKerasGraph",
            "kwargs":{
                "outputs_config":[
                    {
                        "input":"output_act",
                        "name":"default_output_mode_name"
                    }
    ],
                "optimizer_config":{
                    "class":"keras.optimizers.Adam",
                    "kwargs":{
                        "beta_1":0.9,
                        "beta_2":0.999,
                        "lr":0.001
                    }
                },
               "loss_dictionary":{
    "default_output_mode_name":{
    "class": "keras.objectives.get_weighted_binary_crossentropy",
    "kwargs":{
    "w1_weights":[5.37962913731224
,6.40135236664162
,5.60434683265594
,6.15771255553527
,5.36010674931129
,5.06491499227202
,6.10209881941408
,6.35102434737577
,5.82919715388604
,6.27203762824288
,6.26286549933844
,5.43299861728262],
"w0_weights":[1.22832983539188
,1.18513881934012
,1.21718607141139
,1.19388439918522
,1.22935218275515
,1.24600760456274
,1.19599777177872
,1.18688010651464
,1.20707375742473
,1.18967998153938
,1.19001055606033
,1.22558094110415]
    }
                }
},
                "nodes_config":[
                    {
                        "kwargs":{
                            "activity_regularizer":{
                                "kwargs":{
                                    "l1":1e-05
                                },
                                "autoload":true,
                                "class":"keras.regularizers.ActivityRegularizer"
                            },
                            "W_constraint":{
                                "kwargs":{
                                    "m":-1,
                                    "axis":1
                                },
                                "autoload":true,
                                "class":"keras.constraints.maxnorm"
                            },
                            "nb_col":30,
                            "init":"glorot_uniform",
                            "nb_filter":1000,
                            "nb_row":4
                        },
                        "input_name":"default_input_mode_name",
                        "name":"conv1",
                        "class":"keras.layers.convolutional.Convolution2D"
                    },
                    {
                        "kwargs":{
                            "activation":"relu"
                        },
                        "input_name":"conv1",
                        "name":"conv1_act",
                        "class":"keras.layers.core.Activation"
                    },
                    {
                        "kwargs":{
                            "strides":[
                                1,
                                3
                            ],
                            "pool_size":[
                                1,
                                3
                            ]
                        },
                        "input_name":"conv1_act",
                        "name":"avg_pool1",
                        "class":"keras.layers.convolutional.AveragePooling2D"
                    },
                    {
                        "kwargs":{
                            "W_constraint":{
                                "kwargs":{
                                    "m":7,
                                    "axis":1
                                },
                                "autoload":true,
                                "class":"keras.constraints.maxnorm"
                            },
                            "nb_col":11,
                            "W_learning_rate_multiplier":5,
                            "init":"glorot_uniform",
                            "nb_filter":200,
                            "b_learning_rate_multiplier":5,
                            "nb_row":1
                        },
                        "input_name":"avg_pool1",
                        "name":"conv2",
                        "class":"keras.layers.convolutional.Convolution2D"
                    },
                    {
                        "kwargs":{},
                        "input_name":"conv2",
                        "name":"batch_norm2",
                        "class":"keras.layers.normalization.BatchNormalization"
                    },
                    {
                        "kwargs":{
                            "activation":"relu"
                        },
                        "input_name":"batch_norm2",
                        "name":"conv2_act",
                        "class":"keras.layers.core.Activation"
                    },
                    {
                        "kwargs":{
                            "strides":[
                                1,
                                4
                            ],
                            "pool_size":[
                                1,
                                4
                            ]
                        },
                        "input_name":"conv2_act",
                        "name":"avg_pool2",
                        "class":"keras.layers.convolutional.AveragePooling2D"
                    },
                    {
                        "kwargs":{
                            "init":"glorot_uniform",
                            "W_constraint":{
                                "kwargs":{
                                    "m":7,
                                    "axis":1
                                },
                                "autoload":true,
                                "class":"keras.constraints.maxnorm"
                            },
                            "nb_filter":200,
                            "nb_col":7,
                            "nb_row":1
                        },
                        "input_name":"avg_pool2",
                        "name":"conv3",
                        "class":"keras.layers.convolutional.Convolution2D"
                    },
                    {
                        "kwargs":{},
                        "input_name":"conv3",
                        "name":"batch_norm3",
                        "class":"keras.layers.normalization.BatchNormalization"
                    },
                    {
                        "kwargs":{
                            "activation":"relu"
                        },
                        "input_name":"batch_norm3",
                        "name":"conv3_act",
                        "class":"keras.layers.core.Activation"
                    },
                    {
                        "kwargs":{
                            "strides":[
                                1,
                                4
                            ],
                            "pool_size":[
                                1,
                                4
                            ]
                        },
                        "input_name":"conv3_act",
                        "name":"avg_pool3",
                        "class":"keras.layers.convolutional.MaxPooling2D"
                    },
                    {
                        "kwargs":{},
                        "input_name":"avg_pool3",
                        "name":"flatten",
                        "class":"keras.layers.core.Flatten"
                    },
                    {
                        "kwargs":{
                            "activity_regularizer":{
                                "kwargs":{
                                    "l1":0.0001
                                },
                                "autoload":true,
                                "class":"keras.regularizers.ActivityRegularizer"
                            },
                            "output_dim":1000,
                            "W_constraint":{
                                "kwargs":{
                                    "m":7,
                                    "axis":1
                                },
                                "autoload":true,
                                "class":"keras.constraints.maxnorm"
                            },
                            "init":"glorot_uniform"
                        },
                        "input_name":"flatten",
                        "name":"fc_1",
                        "class":"keras.layers.core.Dense"
                    },
                    {
                        "kwargs":{},
                        "input_name":"fc_1",
                        "name":"fc_act1",
                        "class":"keras.layers.advanced_activations.PReLU"
                    },
                    {
                        "kwargs":{
                            "p":0.3
                        },
                        "input_name":"fc_act1",
                        "name":"dropout1",
                        "class":"keras.layers.core.Dropout"
                    },
                    {
                        "kwargs":{
                            "activity_regularizer":{
                                "kwargs":{
                                    "l1":0.0001
                                },
                                "autoload":true,
                                "class":"keras.regularizers.ActivityRegularizer"
                            },
                            "output_dim":1000,
                            "W_constraint":{
                                "kwargs":{
                                    "m":7,
                                    "axis":1
                                },
                                "autoload":true,
                                "class":"keras.constraints.maxnorm"
                            },
                            "init":"glorot_uniform"
                        },
                        "input_name":"dropout1",
                        "name":"fc_2",
                        "class":"keras.layers.core.Dense"
                    },
                    {
                        "kwargs":{},
                        "input_name":"fc_2",
                        "name":"fc_act2",
                        "class":"keras.layers.advanced_activations.PReLU"
                    },
                    {
                        "kwargs":{
                            "p":0.3
                        },
                        "input_name":"fc_act2",
                        "name":"dropout2",
                        "class":"keras.layers.core.Dropout"
                    },
                    {
                        "kwargs":{
                            "activity_regularizer":{
                                "kwargs":{
                                    "l1":0.0001
                                },
                                "autoload":true,
                                "class":"keras.regularizers.ActivityRegularizer"
                            },
                            "output_dim":12,
                            "init":"glorot_uniform"
                        },
                        "input_name":"dropout2",
                        "name":"fc_3",
                        "class":"keras.layers.core.Dense"
                    },
                    {
                        "kwargs":{
                            "activation":"sigmoid"
                        },
                        "input_name":"fc_3",
                        "name":"output_act",
                        "class":"keras.layers.core.Activation"
                    }
                 ],
                "inputs_config":[
                    {
                        "name":"default_input_mode_name",
                        "input_shape":[
                            1,
                            4,
                            2000
                        ]
                    }
                ]
            }
        },
        "model_trainer":{
            "class":"keras_model_trainer.KerasFitGeneratorModelTrainer",
            "kwargs":{
                "stopping_criterion_config":{
                    "class":"EarlyStopping",
                    "kwargs":{
                        "max_epochs":20,
                        "epochs_to_wait":3
                    }
                },
                "nb_worker":1
            }
        },
        "message":"bassetlike",
        "data_loaders":{
            "test":{
                "class":"hdf5_data_loader.MultimodalBatchDataLoader",
                "kwargs":{
                    "path_to_hdf5":"/srv/scratch/annashch/deeplearning/dmso/inputs/newNegativeSet/test_data.hdf5",
                    "bundle_x_and_y_in_generator":true,
                    "use_weights":false,
                    "generator_type":"non_randomized",
                    "batch_size_train":250,
                    "batch_size_predict":250
                }
            },
            "validate":{
                "class":"hdf5_data_loader.MultimodalBatchDataLoader",
                "kwargs":{
                    "path_to_hdf5":"/srv/scratch/annashch/deeplearning/dmso/inputs/newNegativeSet/valid_data.hdf5",
                    "bundle_x_and_y_in_generator":true,
                    "use_weights":false,
                    "generator_type":"non_randomized",
                    "batch_size_train":250,
                    "batch_size_predict":250
                }
            },
            "train":{
                "class":"hdf5_data_loader.MultimodalBatchDataLoader",
                "kwargs":{
                    "path_to_hdf5":"/srv/scratch/annashch/deeplearning/dmso/inputs/newNegativeSet/train_data.hdf5",
                    "bundle_x_and_y_in_generator":true,
                    "use_weights":false,
                    "generator_type":"non_randomized",
                    "batch_size_train":250,
                    "batch_size_predict":250,
                    "num_to_load_for_eval":300000
                }
            }
        }
    }
]